### ISSUE TITLE
Лиценца

### ISSUE THREAD

**Issue by dimztimz** [ikocevski/LanguagePack#1]
Здраво другар.

Забележав дека си искористил дел од мој проект што е лиценциран под ГНУ-ГПЛ. Според лиценцата и твојот проект мора да го лицентираш ислучиво под оваа лиценца.

Друго, користиш и некои транскипти од бомбите (ахахахахахаха), и како што самиот кажа немаат никаква ознака за лиценца. Тие од Хаклаб немале попаметна работа па ги транскирбирале. Правно, со тоа што немаат ознака, не значи дека можеш слободно да ги користиш. Реално, штом не ставиле никаква ознака и туку така ги шитнале на гитхаб, на никого не му е гајле.

Како и да е, и да не користеше ништо од претходново,  ќе ти препорачав на проектот да залепиш Лиценца ГНУ-ГПЛ верзија 3.

**Comment by ikocevski** [comment]
Немав баш некоја идеа, барав натаму наваму и тоа ми дојде онака прво. Се размислив малку, глупо ми дојде да ги ставам тие ама мислев ајде што и онака никој нема да примети.

Проектот ми е WIP како што можеш да видиш и дури сега приметив дека немам ставено лиценца. Не ни разбирам многу како работи ова. Ќе може да ми кажеш што поточно да направам?
Значи бомбите не доаѓаат во предвид, нели? xD

**Comment by dimztimz** [comment]
Знаеш како, доработи го ова до крај, нека го спојат во главното, нека го издадат на АПП-сторе, па после ќе досредуваме, ќе бришеме, ќе додаваме. Сега за сега стави само Лиценца, т.е. стави датотека LICENCE во главната папката. Практично, ископирај ја мојата лиценка од Хунспелл-мк, само смени име на проектот и копирајт тие работи, најгоре смени ги.

**Comment by ikocevski** [comment]
Фала многу.
