### ISSUE TITLE
Корпус на зборови

### ISSUE THREAD

**Issue by dimztimz** [ikocevski/LanguagePack#2]
За добар речник за предвидување потребен ти е корпус на текстови од кои се гради јазичен модел. Ени софт користи наједноствен, јазичен модел со униграми, не зема во предвид соседни последователни зборови.

Речникот што го имаш искористено од кај мене не е добар за предвидување, тој е правен за проверка на правопис. Разговорите што ги имаш се подобри, ама пак ќе речам бомбите лелелееее.

Има еден огромен корпус од 6 гига од македонски текстови (мислам дека е со википедија), од него може да се изгради подобар модел. Ако сакаш да работиш, имав линк до него.

**Comment by ikocevski** [comment]
Океј, 6 гига ми изгледа како да е малку многу ако ме разбираш :D 
Можеби подобро ќе биде да ги избришам помалку пишуваните зборови од твојата листа на зборови?

**Comment by dimztimz** [comment]
Епа не треба да ги пратиш целиот корпус. Локално на твојот комјутер ќе ги изградиш моделот, т.е. ќе измериш честота на секој збор во корспусот. На крајот ќе добиеш датотека од 5-10 мегабајти. Таа датотека еден збор ќе го содржи само еднаш придржен со бројче.

Ама ко што пишав еднаш, нека биде тоа за наредна верзија.

**Comment by ikocevski** [comment]
Од твојот hunspell-mk го симнав /src/pravopisen-recnik.txt ама некои зборови се одвоени со `-` и нов ред, тука има многу работа. Треба рачно да ги спојувам зборовите.

Сега како да направам, да го довршам ова, да го пуштам како што е (со грешки) или да почнам одново со твојот предлог горе?

Како и да е, најди го линкот те молам и прати ми го.

**Comment by dimztimz** [comment]
од ХУнспелл мк, ако ја пуштиш скриптата dicaff.py ќе врти ќе матка и ќе ти исфрли еден речник со 300000 збора, mk-large.dic.Тоа можеш да го искористиш. Ти треба Питон 3. А за линкот од корпусот, да го побарам.

**Comment by ikocevski** [comment]
Леле, како ме спаси, ќе требаше по цели денови да дремам и да ги поправам зборовите еден по еден.
Значи фала ти МНОГУ :D 

Ќе треба да сменам уште некои работи (веројатно build.gradle пак) и ќе им кажам да го пуштат.
Како да те означам некаде дека си ми помогнал?

**Comment by dimztimz** [comment]
Што знам во РЕАДМЕ стави нешто како автор, благодарност, што си искористил.

А за корпусов, линков што го имав изгубен е, ама среќа ја чувам датотеката. Ќе треба некако да ти ја пратам. Само троа голема е хахахахаха. Ќе средиме некако.

Сега ете гледај да се истурка ова до прва верзија што функционира.

**Comment by ikocevski** [comment]
@dimztimz 
Ставив README и на [македонски](https://github.com/ikocevski/LanguagePack/blob/Macedonian/README.md) и на [англиски](https://github.com/ikocevski/LanguagePack/blob/Macedonian/README-EN.md) ако имаш некаква забелешка слободно кажи ми.
Конечно ја објавија апликацијата на [Google Play Store](https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.macedonian) а кај и да е ќе стигне и на [F-Droid](https://f-droid.org/app/com.anysoftkeyboard.languagepack.macedonian).

Сакав да те прашам, како ќе правиме со речникот... Треба да имаме во предвид дека апликацијата сама си го "гради" од plain text датотеки. Тука ми беше проблемот со големината, нели, 6гб.

**Comment by dimztimz** [comment]
1. Change the build.gradle to use and configure the tasks necessary. There are several different variants ([more Information](https://github.com/AnySoftKeyboard/AnySoftKeyboardTools/blob/master/README.md)):
    * `GenerateWordsListTask`
    * `GenerateWordsListFromAOSPTask`
    * `MergeWordsListTask`

„сама си го гради од plain text датотеки“ = GenerateWordsListTask.

Може дополнително да се искросити и MergeWordsListTask

**Comment by ikocevski** [comment]
Немам поим од програмирање ама сакаш да кажеш дека може да се имплементира тој xml фајл што ние треба да го направиме наместо апликацијата, така ? :D 

На пример, зошто мора да ми ги праќаш сите тие фајлови? И онака не знам што ќе им правам... така што, ако знаеш (и сакаш нормално) направи една скрипта и малку магија тука на ГитХаб (merge request со готовиот xml и промените на build.gradle)
Тоа е една опција - практично ќе ставиме и повеќе од "придонесувач" во README.

Ако немаш време и слично, мене пак ќе ми треба скрипта (што не знам да ја направам) за да го добијам речникот. Значи, како и да е има зафрканции околу ова. Плус ќе треба да се замараме со качување на тие 6 гб па јас да ги симнувам.

**Comment by ikocevski** [comment]
@dimztimz Мм?

**Comment by dimztimz** [comment]
Не мора посебна скрипта може да се искористат нивните скрипти/функции.

прво во build.gradle ќе се пушти GenerateWordlist за од тие 6 гига да се добие .xml и после се брише тоа од build.gradle, се бришат и 6те гига и се става mergewordlist во build.gradle

**Comment by ikocevski** [comment]
@dimztimz Аха... Е сега океј е тоа сѐ, само што кај мене на Android Studio воопшто не поминуваше build кога ги ставив датотеките за речникот. Ми покажуваше некаква грешка додека сосема истиот проект работеше кај friesenkiwi (оддржувач на ASK).

Ќе може некако без Android Studio?

**Comment by ikocevski** [comment]
@dimztimz Еве пробав само со gradle да направам build овој пат од Linux.
Колку треба да сум баксуз ајде кажи ми...

https://paste.fedoraproject.org/paste/Ap2kzEbVyWFK3164TjtR~w

**Comment by dimztimz** [comment]
Абе за билд да проработи треба ова https://github.com/AnySoftKeyboard/AnySoftKeyboardTools а многу веројатно и главното https://github.com/AnySoftKeyboard/AnySoftKeyboard

Треба прво тие да се компајлираат па некако да се поврзат со тастатурава.

**Comment by ikocevski** [comment]
Е аман бе толку компликации за тастатура. Ќе пробам утре ајде.
